[package]
name = "coordinator-test-utils"
version = "0.1.0"
edition = "2021"

[dependencies]
coordinator = { path = "../..", features = ["arbitrary"] }
proptest = "1.9.0"
proptest-derive = "0.5.1"
serde_json = "1.0"
