[package]
name = "coordinator"
version = "0.1.0"
edition = "2024"

[dependencies]
catalog.workspace = true
model.workspace = true
reconciler.workspace = true
madsim.workspace = true
tonic.workspace = true
prost.workspace = true
flume.workspace = true
tokio.workspace = true
tracing.workspace = true
anyhow.workspace = true
thiserror.workspace = true
itertools.workspace = true

[build-dependencies]
tonic-build.workspace = true
